### PR TITLE
Add Variance and Standard Deviation for Columns

### PR DESCRIPTION
**Pull request by GrandathePanda**
I do a decent amount of data manipulations and I like your plugin for vim and just wanted to add a few more statistical functions.

### CODE REVIEW

**Comment by chrisbra** [comment]
Great, thanks! Can you please also update doc/ft-csv.txt It shouldn't be too hard, it basically needs the information of README.md adjusted by some basic formatting.

**Comment by GrandathePanda** [comment]
Yup no problem, I will get to that in a little bit

**Comment by GrandathePanda** [comment]
@chrisbra Should be in there now.

**Comment by chrisbra** [comment]
Thanks!

**Pull request merged**
